services:
  toggl-track-exporter:
    image: ghcr.io/echohello-dev/prometheus-toggl-track-exporter:latest
    container_name: toggl-track-exporter
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - TOGGL_API_TOKEN=${TOGGL_API_TOKEN}
      - EXPORTER_PORT=9090
      # METRICS_PATH is not needed by the client, but can be kept for reference
      # - METRICS_PATH=/metrics
      - COLLECTION_INTERVAL=60
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
