{{- if .Values.injectSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.injectSecrets.secretName | default (printf "%s-secret" (include "prometheus-toggl-track-exporter.fullname" .)) }}
  labels:
    {{- include "prometheus-toggl-track-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  # Store the API token using the environment variable name expected by the application
  TOGGL_API_TOKEN: {{ .Values.toggl.apiToken | b64enc | quote }}
{{- end }}
