apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-toggl-track-exporter
  namespace: monitoring
  labels:
    app: prometheus-toggl-track-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-toggl-track-exporter
  template:
    metadata:
      labels:
        app: prometheus-toggl-track-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: exporter
          image: ghcr.io/echohello-dev/prometheus-toggl-track-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: EXPORTER_PORT
              value: "9090"
            - name: COLLECTION_INTERVAL
              value: "60"
            - name: TIME_ENTRIES_LOOKBACK_HOURS
              value: "24"
            - name: TOGGL_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: toggl-secret
                  key: TOGGL_API_TOKEN
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # Liveness/Readiness probes can be added here if needed
          # livenessProbe:
          #   httpGet:
          #     path: / # Simple check if server is running
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: / # Simple check if server is running
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
