apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - prometheus-config.yaml
namespace: monitoring

commonLabels:
  app.kubernetes.io/name: prometheus-toggl-track-exporter
