apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Example job for scraping the Toggl Track exporter
      - job_name: 'toggl-track-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring # Assumes exporter runs in monitoring namespace
        relabel_configs:
          # Find pods with the correct app label
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: prometheus-toggl-track-exporter
          # Scrape pods with the prometheus.io/scrape annotation
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Use the scrape path annotation
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use the scrape port annotation
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          # Use pod name as instance label
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: instance
