apiVersion: v1
kind: Secret
metadata:
  name: toggl-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-toggl-track-exporter
type: Opaque
data:
  # Key name must match the environment variable expected by the Deployment
  TOGGL_API_TOKEN: <BASE64_ENCODED_API_TOKEN>
