apiVersion: v1
kind: Service
metadata:
  name: prometheus-toggl-track-exporter
  namespace: monitoring
  labels:
    app: prometheus-toggl-track-exporter
spec:
  selector:
    app: prometheus-toggl-track-exporter
  ports:
    - protocol: TCP
      port: 9090
      targetPort: http
      name: http
  type: ClusterIP
